version: "3.8"

services:
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka_local
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1 # Уникальный номер сервера в кластере
      KAFKA_PROCESS_ROLES: "broker,controller" # Сообщает KRaft что этот сервер отвечает за ажминистирование и хранение даннызх
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:29093"
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk" # Уникальный ID Кластера

      # Открытие портов и их alias
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092" #
      # Настройка подключения (При первом подключении кавка отправляет адрес:порт для подклчения)
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092"
      # Настройки безопасноти PLAINTEXT - без шифрования
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # Слешаем адрес:порт для системных команд (внутрення сеть, а не публичный аддрес)
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"

      # KAFKA_OFFSETS_TOPIC_NUM_PARTITIONS: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  # service_first:
  # service_second:
